version: '3'
services:
  www:
    image: ghcr.io/letright/xb-docker:php-fpm81
    container_name: xboard
    volumes:
      - './www:/www'
      - './wwwlogs:/wwwlogs'
      - './Caddyfile:/run/caddy/Caddyfile'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './cert:/cert'
    ports:
    - "28443:443"
    restart: always
